[package]
name = "daylight"
version = "0.1.0"
edition = "2024"

build = "build.rs"

[dependencies]
capnp = "0.23.0"
capnp-futures = "0.23.0"
capnp-rpc = "0.23.0"
futures = "0.3"
rayon = "1.11.0"
thiserror = "2.0.17"
tokio = { version = "1", features = ["net", "rt", "macros", "time"]}
tokio-util = { version = "0.7", features = ["compat"] }
tree-sitter = "0.25.10"
tree-sitter-agda = "1.3.0"
tree-sitter-bash = "0.25.1"
tree-sitter-c = "0.24.1"
tree-sitter-highlight = "0.25.10"

[build-dependencies]
capnpc = "0.23.2"
