[package]
name = "daylight"
version = "0.1.0"
edition = "2024"

build = "build.rs"

[dependencies]
capnp = { version = "0.23.0", features = ["quickcheck"] }
capnp-futures = "0.23.0"
capnp-rpc = "0.23.0"
futures = "0.3"
rayon = "1.11.0"
tokio = { version = "1", features = ["net", "rt", "macros"]}
tokio-util = { version = "0.7", features = ["compat"] }

[build-dependencies]
capnpc = "0.23.2"
